"""init guest field

Revision ID: 728b491a3ea4
Revises: 
Create Date: 2025-04-06 13:28:57.069202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '728b491a3ea4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('natal_charts', sa.Column('session_token', sa.String(), nullable=True))
    op.alter_column('natal_charts', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_natal_charts_session_token'), 'natal_charts', ['session_token'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_natal_charts_session_token'), table_name='natal_charts')
    op.alter_column('natal_charts', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('natal_charts', 'session_token')
    # ### end Alembic commands ###
